/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indexing/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Indexing Profiles */
        get: operations["indexing_profiles_api_v1_indexing_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indexing/parsers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source Parsers */
        get: operations["source_parsers_api_v1_indexing_parsers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indexing/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Indexing */
        post: operations["preview_indexing_api_v1_indexing_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indexing/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Indexing Job */
        get: operations["get_indexing_job_api_v1_indexing_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indexing/jobs/{job_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Indexing Artifacts */
        get: operations["get_indexing_artifacts_api_v1_indexing_jobs__job_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/retrieval/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Retrieval */
        post: operations["search_retrieval_api_v1_retrieval_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/retrieval/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer Retrieval */
        post: operations["answer_retrieval_api_v1_retrieval_answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Source */
        post: operations["create_source_api_v1_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Source */
        post: operations["upload_source_api_v1_sources_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source_id}/index/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Source Indexing */
        post: operations["preview_source_indexing_api_v1_sources__source_id__index_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source_id}/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Source Indexing */
        post: operations["run_source_indexing_api_v1_sources__source_id__index_post"];
        /** Delete Source Index */
        delete: operations["delete_source_index_api_v1_sources__source_id__index_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source_id}/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Source Nodes */
        get: operations["list_source_nodes_api_v1_sources__source_id__nodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerCitationResponse */
        AnswerCitationResponse: {
            /** Citation Id */
            citation_id: string;
            /** Context Id */
            context_id: string;
            /** Source Id */
            source_id: string;
            /** Node Id */
            node_id: string;
            /** Filename */
            filename: string | null;
            /** Page Label */
            page_label: string | null;
            /** Section Path */
            section_path: string[];
        };
        /** Body_upload_source_api_v1_sources_upload_post */
        Body_upload_source_api_v1_sources_upload_post: {
            /** File */
            file: string;
            /** Notebook Id */
            notebook_id: string;
            /** Source Id */
            source_id?: string | null;
            /** Metadata */
            metadata?: string | null;
        };
        /** ContentBlockPayload */
        ContentBlockPayload: {
            /** Block Id */
            block_id?: string | null;
            /**
             * Block Type
             * @default text
             */
            block_type: string;
            /**
             * Text
             * @default
             */
            text: string;
            /** Page No */
            page_no?: number | null;
            /** Bbox */
            bbox?: [
                number,
                number,
                number,
                number
            ] | null;
            /** Section Hint */
            section_hint?: string[];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** ContentBlockResponse */
        ContentBlockResponse: {
            /** Block Id */
            block_id: string;
            /** Source Id */
            source_id: string;
            /** Block Type */
            block_type: string;
            /** Text */
            text: string;
            /** Page No */
            page_no: number | null;
            /** Bbox */
            bbox: [
                number,
                number,
                number,
                number
            ] | null;
            /** Section Hint */
            section_hint: string[];
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** CreateSourceRequest */
        CreateSourceRequest: {
            /** Source Id */
            source_id?: string | null;
            /** Notebook Id */
            notebook_id: string;
            /** Filename */
            filename: string;
            /** Media Type */
            media_type: string;
            /** Text */
            text?: string | null;
            /** Blocks */
            blocks?: components["schemas"]["ContentBlockPayload"][];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** DeleteSourceIndexResponse */
        DeleteSourceIndexResponse: {
            /** Source Id */
            source_id: string;
            /** Deleted Count */
            deleted_count: number;
            /** Vector Deleted Count */
            vector_deleted_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IndexBlockResponse */
        IndexBlockResponse: {
            /** Block Id */
            block_id: string;
            /** Job Id */
            job_id: string;
            /** Source Id */
            source_id: string;
            /** Notebook Id */
            notebook_id: string;
            /** Order Index */
            order_index: number;
            /** Block Type */
            block_type: string;
            /** Text */
            text: string;
            /** Page No */
            page_no: number | null;
            /** Bbox */
            bbox: [
                number,
                number,
                number,
                number
            ] | null;
            /** Section Hint */
            section_hint: string[];
            /** Parser Name */
            parser_name: string | null;
            /** Parser Version */
            parser_version: string | null;
            /** Content Hash */
            content_hash: string | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** IndexJobResponse */
        IndexJobResponse: {
            /** Job Id */
            job_id: string;
            /** Source Id */
            source_id: string;
            /** Status */
            status: string;
            /** Requested Profile */
            requested_profile: string | null;
            /** Effective Profile */
            effective_profile: string | null;
            /** Requested Parser */
            requested_parser: string | null;
            /** Effective Parser */
            effective_parser: string | null;
            /** Overrides */
            overrides: {
                [key: string]: unknown;
            };
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
            /** Error Message */
            error_message: string | null;
            /** Vector Status */
            vector_status: string | null;
            /** Vector Error Message */
            vector_error_message: string | null;
            /** Node Count */
            node_count: number;
        };
        /** IndexNodeResponse */
        IndexNodeResponse: {
            /** Node Id */
            node_id: string;
            /** Source Id */
            source_id: string;
            /** Notebook Id */
            notebook_id: string;
            /** Text */
            text: string;
            /** Modality */
            modality: string;
            /** Content Type */
            content_type: string;
            /** Page Start */
            page_start: number | null;
            /** Page End */
            page_end: number | null;
            /** Section Path */
            section_path: string[];
            /** Block Ids */
            block_ids: string[];
            /** Parent Node Id */
            parent_node_id: string | null;
            /** Asset Path */
            asset_path: string | null;
            /** Bbox */
            bbox: [
                number,
                number,
                number,
                number
            ] | null;
            /** Indexing Profile */
            indexing_profile: string | null;
            /** Parser Version */
            parser_version: string | null;
            /** Chunker Version */
            chunker_version: string | null;
            /** Embedding Model */
            embedding_model: string | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** IndexingArtifactsResponse */
        IndexingArtifactsResponse: {
            job: components["schemas"]["IndexJobResponse"];
            /** Blocks */
            blocks: components["schemas"]["IndexBlockResponse"][];
            /** Nodes */
            nodes: components["schemas"]["IndexNodeResponse"][];
            /** Vectorized Node Ids */
            vectorized_node_ids: string[];
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
        };
        /** IndexingPreviewRequest */
        IndexingPreviewRequest: {
            /** Profile Name */
            profile_name?: string | null;
            /** Parser Name */
            parser_name?: string | null;
            /** Parser Options */
            parser_options?: {
                [key: string]: unknown;
            };
            overrides?: components["schemas"]["ProfileOverridesPayload"];
            source: components["schemas"]["SourcePayload"];
        };
        /** IndexingPreviewResponse */
        IndexingPreviewResponse: {
            analysis: components["schemas"]["SourceAnalysisResponse"];
            effective_profile: components["schemas"]["IndexingProfileResponse"];
            /** Effective Parser */
            effective_parser: string;
            /** Blocks */
            blocks: components["schemas"]["ContentBlockResponse"][];
            /** Nodes */
            nodes: components["schemas"]["IndexNodeResponse"][];
            summary: components["schemas"]["IndexingSummaryResponse"];
        };
        /** IndexingProfileResponse */
        IndexingProfileResponse: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Chunker */
            chunker: string;
            /** Chunk Size */
            chunk_size: number;
            /** Chunk Overlap */
            chunk_overlap: number;
            /** Node Graph Mode */
            node_graph_mode: string;
            /** Supported Media Types */
            supported_media_types: string[];
            /** Text Collection */
            text_collection: string;
            /** Visual Collection */
            visual_collection: string;
            /** Options */
            options: {
                [key: string]: unknown;
            };
        };
        /** IndexingSummaryResponse */
        IndexingSummaryResponse: {
            /** Block Count */
            block_count: number;
            /** Node Count */
            node_count: number;
            /** Page Count */
            page_count: number;
            /** Block Types */
            block_types: {
                [key: string]: number;
            };
            /** Content Types */
            content_types: {
                [key: string]: number;
            };
            /** Modalities */
            modalities: {
                [key: string]: number;
            };
            /** Node Roles */
            node_roles: {
                [key: string]: number;
            };
            /** Vectorized Count */
            vectorized_count: number;
            /** Chunk Length Stats */
            chunk_length_stats: {
                [key: string]: number;
            };
            /** Quality */
            quality: {
                [key: string]: unknown;
            };
            /** Performance */
            performance: {
                [key: string]: number;
            };
        };
        /** ProfileOverridesPayload */
        ProfileOverridesPayload: {
            /** Chunk Size */
            chunk_size?: number | null;
            /** Chunk Overlap */
            chunk_overlap?: number | null;
            /** Options */
            options?: {
                [key: string]: unknown;
            };
        };
        /** RetrievalAnswerRequest */
        RetrievalAnswerRequest: {
            /** Query */
            query: string;
            /** Notebook Id */
            notebook_id: string;
            /** Retrieval Top K */
            retrieval_top_k?: number | null;
            /** Rerank Top K */
            rerank_top_k?: number | null;
            /** Source Ids */
            source_ids?: string[];
            /** Content Types */
            content_types?: string[];
            /** Score Threshold */
            score_threshold?: number | null;
        };
        /** RetrievalAnswerResponse */
        RetrievalAnswerResponse: {
            /** Query */
            query: string;
            /** Notebook Id */
            notebook_id: string;
            /** Answer */
            answer: string;
            /** Retrieval Count */
            retrieval_count: number;
            /** Rerank Count */
            rerank_count: number;
            /** Reranker */
            reranker: string;
            /** Answer Generator */
            answer_generator: string;
            /** Contexts */
            contexts: components["schemas"]["RetrievalContextResponse"][];
            /** Citations */
            citations: components["schemas"]["AnswerCitationResponse"][];
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** RetrievalCitationResponse */
        RetrievalCitationResponse: {
            /** Source Id */
            source_id: string;
            /** Node Id */
            node_id: string;
            /** Filename */
            filename: string | null;
            /** Page Label */
            page_label: string | null;
            /** Section Path */
            section_path: string[];
        };
        /** RetrievalContextResponse */
        RetrievalContextResponse: {
            /** Context Id */
            context_id: string;
            /** Citation Id */
            citation_id: string;
            /** Node Id */
            node_id: string;
            /** Source Id */
            source_id: string;
            /** Notebook Id */
            notebook_id: string;
            /** Text */
            text: string;
            /** Score */
            score: number;
            /** Vector Score */
            vector_score: number;
            /** Rerank Score */
            rerank_score: number;
            /** Collection Name */
            collection_name: string;
            /** Content Type */
            content_type: string;
            /** Page Start */
            page_start: number | null;
            /** Page End */
            page_end: number | null;
            /** Section Path */
            section_path: string[];
            citation: components["schemas"]["RetrievalCitationResponse"];
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** RetrievalSearchRequest */
        RetrievalSearchRequest: {
            /** Query */
            query: string;
            /** Notebook Id */
            notebook_id: string;
            /**
             * Top K
             * @default 8
             */
            top_k: number;
            /** Source Ids */
            source_ids?: string[];
            /** Content Types */
            content_types?: string[];
            /** Score Threshold */
            score_threshold?: number | null;
        };
        /** RetrievalSearchResponse */
        RetrievalSearchResponse: {
            /** Query */
            query: string;
            /** Notebook Id */
            notebook_id: string;
            /** Count */
            count: number;
            /** Results */
            results: components["schemas"]["RetrievedNodeResponse"][];
        };
        /** RetrievedNodeResponse */
        RetrievedNodeResponse: {
            /** Node Id */
            node_id: string;
            /** Source Id */
            source_id: string;
            /** Notebook Id */
            notebook_id: string;
            /** Text */
            text: string;
            /** Score */
            score: number;
            /** Collection Name */
            collection_name: string;
            /** Content Type */
            content_type: string;
            /** Page Start */
            page_start: number | null;
            /** Page End */
            page_end: number | null;
            /** Section Path */
            section_path: string[];
            citation: components["schemas"]["RetrievalCitationResponse"];
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** RunIndexJobRequest */
        RunIndexJobRequest: {
            /** Profile Name */
            profile_name?: string | null;
            /** Parser Name */
            parser_name?: string | null;
            /** Parser Options */
            parser_options?: {
                [key: string]: unknown;
            };
            overrides?: components["schemas"]["ProfileOverridesPayload"];
        };
        /** RunIndexJobResponse */
        RunIndexJobResponse: {
            job: components["schemas"]["IndexJobResponse"];
            source: components["schemas"]["SourceResponse"];
            effective_profile: components["schemas"]["IndexingProfileResponse"];
            /** Effective Parser */
            effective_parser: string;
            summary: components["schemas"]["IndexingSummaryResponse"];
            /** Node Count */
            node_count: number;
        };
        /** SourceAnalysisResponse */
        SourceAnalysisResponse: {
            /** Recommended Profile */
            recommended_profile: string;
            /** Reasons */
            reasons: string[];
            /** Traits */
            traits: {
                [key: string]: unknown;
            };
        };
        /** SourceParserResponse */
        SourceParserResponse: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Supported Extensions */
            supported_extensions: string[];
            /** Supported Media Types */
            supported_media_types: string[];
            /** Requires Api Key */
            requires_api_key: boolean;
            /** Is Default */
            is_default: boolean;
            /** Is Internal */
            is_internal: boolean;
        };
        /** SourcePayload */
        SourcePayload: {
            /**
             * Source Id
             * @default preview-source
             */
            source_id: string;
            /**
             * Notebook Id
             * @default preview-notebook
             */
            notebook_id: string;
            /**
             * Filename
             * @default preview.txt
             */
            filename: string;
            /**
             * Media Type
             * @default text/plain
             */
            media_type: string;
            /** Text */
            text?: string | null;
            /** Blocks */
            blocks?: components["schemas"]["ContentBlockPayload"][];
            /** File Path */
            file_path?: string | null;
            /** File Size */
            file_size?: number | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** SourceResponse */
        SourceResponse: {
            /** Source Id */
            source_id: string;
            /** Notebook Id */
            notebook_id: string;
            /** Filename */
            filename: string;
            /** Media Type */
            media_type: string;
            /** Source Hash */
            source_hash: string;
            /** Text */
            text: string | null;
            /** Input Blocks */
            input_blocks: {
                [key: string]: unknown;
            }[];
            /** Has File */
            has_file: boolean;
            /** File Size */
            file_size: number | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    indexing_profiles_api_v1_indexing_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexingProfileResponse"][];
                };
            };
        };
    };
    source_parsers_api_v1_indexing_parsers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceParserResponse"][];
                };
            };
        };
    };
    preview_indexing_api_v1_indexing_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IndexingPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexingPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_indexing_job_api_v1_indexing_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_indexing_artifacts_api_v1_indexing_jobs__job_id__artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexingArtifactsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_retrieval_api_v1_retrieval_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetrievalSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrievalSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_retrieval_api_v1_retrieval_answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetrievalAnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrievalAnswerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_source_api_v1_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSourceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_source_api_v1_sources_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_source_api_v1_sources_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_source_indexing_api_v1_sources__source_id__index_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunIndexJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexingPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_source_indexing_api_v1_sources__source_id__index_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunIndexJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunIndexJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_source_index_api_v1_sources__source_id__index_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteSourceIndexResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_source_nodes_api_v1_sources__source_id__nodes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexNodeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
